steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - spez-archiver
      - --runtime=go113
      - --entry-point=archiver
      - --trigger-topic=spez_poller_table
      - --source=cloud-functions/.
